services:
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # RabbitMQ messaging port
      - "15672:15672"   # Management interface
    environment:
      RABBITMQ_DEFAULT_USER: guest    # Default username
      RABBITMQ_DEFAULT_PASS: guest    # Default password
